### ISSUE TITLE
Can't send tokens using the Keplr wallet

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1231]
<img width="357" alt="Screenshot 2023-10-03 at 20 57 38" src="https://github.com/zeta-chain/node/assets/332151/cd629786-8ce1-4e81-a7b1-46c05638877e">

<img width="370" alt="Screenshot 2023-10-03 at 20 56 54" src="https://github.com/zeta-chain/node/assets/332151/f0767457-5af1-4a28-8ced-e53194e242ef">

Console:

```
POST https://zetachain-athens.blockpi.network/lcd/v1/public/cosmos/tx/v1beta1/simulate 400 (Bad Request)

Error: Failed to get response from https://zetachain-athens.blockpi.network/cosmos/tx/v1beta1/simulate
    at 351.bundle.js:2:451996
    at Generator.next (<anonymous>)
    at a (351.bundle.js:2:450458)

Error: Failed to get response from https://zetachain-athens.blockpi.network/cosmos/tx/v1beta1/txs
    at t.InExtensionMessageRequester.<anonymous> (244.bundle.js:2:1085778)
    at Generator.next (<anonymous>)
    at s (244.bundle.js:2:1085004)
```

In the Networks tab there is only one POST request and it's failing:

```
POST https://zetachain-athens.blockpi.network/lcd/v1/public/cosmos/tx/v1beta1/simulate

{"tx_bytes": "CpsBCpgBChwvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dTZW5kEngKK3pldGExOW5mYXF1OXdyMGZrdHl5YW1wdmE5OGVjMDI1a2p5MHBod3c1dW0SK3pldGExM3J5eXJ3ZXlwODQ5azNoYXJ3dHpmMHE3ODdxc2hnd212bHkycnMaHAoFYXpldGESEzEwMDAwMDAwMDAwMDAwMDAwMDASKQoJEgQKAgh/GI8EEhwKGgoFYXpldGESETEyNDEwNTYwMDAwMDAwMDAwGkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}
```

I guess Keplr is trying to simulate the tx first and it's not working as expected.

**Comment by CharlieMc0** [comment]
@fadeev did this break the same time we changed the Bip32 HD path?

**Comment by ws4charlie** [comment]
Keplr works well. I think we can close this issue for now.
