### ISSUE TITLE
full node cannot be started, "nodeAcountList" panic error

### ISSUE THREAD

**Issue by Fabryprog** [zeta-chain/node#1412]
Hello everyone, I am trying to install a testnet full node but, following the official documentation, I have the error:

``
8:38AM INF Unlocking keyring
8:38AM INF starting ABCI with Tendermint
8:38AM INF starting node with ABCI Tendermint in-process
8:38AM INF service start impl=multiAppConn module=proxy msg={} server=node
8:38AM INF service start connection=query impl=localClient module=abci-client msg={} server=node
8:38AM INF service start connection=snapshot impl=localClient module=abci-client msg={} server=node
8:38AM INF service start connection=mempool impl=localClient module=abci-client msg={} server=node
8:38AM INF service start connection=consensus impl=localClient module=abci-client msg={} server=node
8:38AM INF service start impl=EventBus module=events msg={} server=node
8:38AM INF service start impl=PubSub module=pubsub msg={} server=node
8:38AM INF service start impl=IndexerService module=txindex msg={} server=node
8:38AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 server=node software-version=10.1.4
8:38AM INF ABCI Replay Blocks appHeight=0 module=consensus server=node stateHeight=0 storeHeight=0
8:38AM INF initializing blockchain state from genesis.json
8:38AM INF asserting crisis invariants inv=1/12 module=x/crisis name=distribution/nonnegative-outstanding
8:38AM INF asserting crisis invariants inv=2/12 module=x/crisis name=distribution/can-withdraw
8:38AM INF asserting crisis invariants inv=3/12 module=x/crisis name=distribution/reference-count
8:38AM INF asserting crisis invariants inv=4/12 module=x/crisis name=distribution/module-account
8:38AM INF asserting crisis invariants inv=5/12 module=x/crisis name=staking/module-accounts
8:38AM INF asserting crisis invariants inv=6/12 module=x/crisis name=staking/nonnegative-power
8:38AM INF asserting crisis invariants inv=7/12 module=x/crisis name=staking/positive-delegation
8:38AM INF asserting crisis invariants inv=8/12 module=x/crisis name=staking/delegator-shares
8:38AM INF asserting crisis invariants inv=9/12 module=x/crisis name=gov/module-account
8:38AM INF asserting crisis invariants inv=10/12 module=x/crisis name=bank/nonnegative-outstanding
8:38AM INF asserting crisis invariants inv=11/12 module=x/crisis name=bank/total-supply
8:38AM INF asserting crisis invariants inv=12/12 module=x/crisis name=group/Group-TotalWeight
8:38AM INF asserted all invariants duration=0.828137 height=0 module=x/crisis
panic: unknown field "nodeAccountList" in types.GenesisState

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x45?, {0xc001f3d000?, 0xc00106d2c0?, 0x1?}, {0x3d155c0?, 0xc000f1da40?})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/codec/proto_codec.go:187 +0x45
github.com/zeta-chain/zetacore/x/crosschain.AppModule.InitGenesis({{{0x3d38738, 0xc000de3140}}, {{0x3d38738, 0xc000de3140}, {0x3cfd430, 0xc001d19380}, {0x3cfd430, 0x0}, {0x3cfd660, 0xc001291600}, ...}, ...}, ...)
	/go/src/github.com/zeta-chain/node/x/crosschain/module.go:167 +0xa2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x3d1ad20, 0xc000054068}, {0x3d30260, 0xc001f0e780}, {{0x0, 0x0}, {0xc001d88aa0, 0xd}, 0x0, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/types/module/module.go:322 +0x363
github.com/zeta-chain/zetacore/app.(*App).InitChainer(_, {{0x3d1ad20, 0xc000054068}, {0x3d30260, 0xc001f0e780}, {{0x0, 0x0}, {0xc001d88aa0, 0xd}, 0x0, ...}, ...}, ...)
	/go/src/github.com/zeta-chain/node/app/app.go:618 +0x12e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0014f0700, {{0x1d6dd810, 0xedc005e93, 0x0}, {0xc001d88aa0, 0xd}, 0xc001072180, {0x5666b40, 0x0, 0x0}, ...})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/baseapp/abci.go:71 +0x3f5
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc001dd2c60, {{0x1d6dd810, 0xedc005e93, 0x0}, {0xc001d88aa0, 0xd}, 0xc001072180, {0x5666b40, 0x0, 0x0}, ...})
	/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc00105a080?, {{0x1d6dd810, 0xedc005e93, 0x0}, {0xc001d88aa0, 0xd}, 0xc001072180, {0x5666b40, 0x0, 0x0}, ...})
	/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2d6209c, 0x7}}, {0xc001d88aa0, 0xd}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/consensus/replay.go:319 +0xf18
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000e7cf90, {0x3d33990, 0xc001e101a0})
	/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2d6209c, 0x7}}, {0xc001d88aa0, 0xd}, 0x1, 0x0, ...}, ...)
	/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0000fe640, {0x3d13580, 0xc001d66fa0}, 0xc001d71b90, {0x3cf3900, 0xc001d7adf8}, 0x1?, 0x5666b40?, 0xc001d71db0, {0x3d1c7d0, ...}, ...)
	/root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/node/node.go:779 +0x597
github.com/zeta-chain/zetacore/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3d46ee0, 0xc0017c2420}, 0x0, {0x0, 0x0}, {0x3d38738, ...}, ...}, ...)
	/go/src/github.com/zeta-chain/node/server/start.go:380 +0xf47
github.com/zeta-chain/zetacore/server.StartCmd.func2(0xc001617200?, {0x5666b40?, 0x0?, 0x0?})
	/go/src/github.com/zeta-chain/node/server/start.go:164 +0x2a5
github.com/spf13/cobra.(*Command).execute(0xc001617200, {0x5666b40, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0014fc300)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x266e4a0?, {0x0, 0x0}, {0xc0014f91e0, 0x1a})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/server/cmd/execute.go:36 +0x20f
main.main()
	/go/src/github.com/zeta-chain/node/cmd/zetacored/main.go:19 +0x35
```

I am using the [v10.1.4](https://github.com/zeta-chain/node/releases/tag/v10.1.4) version!

Thanks

**Comment by Fabryprog** [comment]
Any news regarding this bug?

**Comment by kingpinXD** [comment]
It's not possible to start a node from Genesis using a newer binary. Please use the statesync option to start your node
