### ISSUE TITLE
Upgrade handler issue in zetacord v12.0.4

### ISSUE THREAD

**Issue by CryptoFewka** [zeta-chain/node#1676]
User is getting an error when trying to upgrade v11 to v12 at height 1424500 on mainnet. 

They were moving from v11.0.5 to 12.0.4 at block 1424500.

I asked that they use v12.0.0 instead, and then v12.2.1 at the next upgrade for Mainnet at 1549750.

A working full upgrade path for zetacord to sync from scratch for Mainnet is expected to be:

1257000 - v11.0.0
1424500 - v12.0.0
1529050 - v12.1.0
1549750 - v12.2.1

```
 Replay last block using real app module=consensus server=node
 8:54AM INF applying upgrade "v12.0.0" at height: 1424500
 8:54AM INF Running upgrade handler for v12.0.0
 8:54AM INF migrating module crosschain from version 3 to version 4
 8:54AM INF migrating module observer from version 4 to version 5
 panic: runtime error: index out of range [0] with length 0
 goroutine 1 [running]:
 github.com/zeta-chain/zetacore/x/observer/migrations/v5.MigrateObserverMapper({{0x3d76f98, 0xc0001a4000}, {0x3d8c600, 0xc00012a7c0}, {{0xb, 0x0}, {0xc000709aa0, 0x10}, 0x15bc74, {0xcfae9d2, ...}, ...}, ...}, ...)
  /go/src/github.com/zeta-chain/node/x/observer/migrations/v5/migrate.go:40 +0x79d
 github.com/zeta-chain/zetacore/x/observer/migrations/v5.MigrateStore({{0x3d76f98, 0xc0001a4000}, {0x3d8c600, 0xc00012a7c0}, {{0xb, 0x0}, {0xc000709aa0, 0x10}, 0x15bc74, {0xcfae9d2, ...}, ...}, ...}, ...)
  /go/src/github.com/zeta-chain/node/x/observer/migrations/v5/migrate.go:22 +0xae
 github.com/zeta-chain/zetacore/x/observer/keeper.Migrator.Migrate4to5(...)
  /go/src/github.com/zeta-chain/node/x/observer/keeper/migrator.go:38
 github.com/cosmos/cosmos-sdk/types/module.configurator.runModuleMigrations({{_, _}, {_, _}, {_, _}, _}, {{0x3d76f98, 0xc0001a4000}, {0x3d8c600, ...}, ...}, ...)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/types/module/configurator.go:110 +0x335
 github.com/cosmos/cosmos-sdk/types/module.Manager.RunMigrations({0xc000da8f60, {0xc0013bb680, 0x14, 0x14}, {0xc0013bb040, 0x14, 0x14}, {0xc0013bb180, 0x14, 0x14}, ...}, ...)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/types/module/module.go:455 +0x4e9
 github.com/zeta-chain/zetacore/app.SetupHandlers.func1({{0x3d76f98, 0xc0001a4000}, {0x3d8c600, 0xc00012a7c0}, {{0xb, 0x0}, {0xc000709aa0, 0x10}, 0x15bc74, {0xcfae9d2, ...}, ...}, ...}, ...)
  /go/src/github.com/zeta-chain/node/app/setup_handlers.go:23 +0x265
 github.com/cosmos/cosmos-sdk/x/upgrade/keeper.Keeper.ApplyUpgrade({{0x7ffc0f3a6e32, 0x1d}, 0xc001f4b9e0, {0x3d58e90, 0xc001e2a600}, {0x3d8bbf0, 0xc00101a010}, 0xc000da8c00, {0x3d4cfc0, 0xc000d26000}, ...}, ...)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/x/upgrade/keeper/keeper.go:337 +0x19e
 github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7ffc0f3a6e32, 0x1d}, 0xc001f4b9e0, {0x3d58e90, 0xc001e2a600}, {0x3d8bbf0, 0xc00101a010}, 0xc000da8c00, {0x3d4cfc0, 0xc000d26000}, ...}, ...)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/x/upgrade/abci.go:62 +0x66c
 github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/x/upgrade/module.go:134
 github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x3d76f98, 0xc0001a4000}, {0x3d8c600, 0xc00012a7c0}, {{0xb, 0x0}, {0xc000709aa0, 0x10}, 0x15bc74, ...}, ...}, ...)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/types/module/module.go:484 +0x1bb
 github.com/zeta-chain/zetacore/app.(*App).BeginBlocker(...)
  /go/src/github.com/zeta-chain/node/app/app.go:616
 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0019a37a0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000709aa0, 0x10}, 0x15bc74, {0xcfae9d2, ...}, ...}, ...})
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/baseapp/abci.go:183 +0x843
 github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0019a37a0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000709aa0, 0x10}, 0x15bc74, {0xcfae9d2, ...}, ...}, ...})
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/abci/client/local_client.go:280 +0x118
 github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0019a37a0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000709aa0, 0x10}, 0x15bc74, {0xcfae9d2, ...}, ...}, ...})
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/proxy/app_conn.go:81 +0x55
 github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x3d78a48?, 0xc0001a1620}, {0x3d82d20, 0xc0016933f0}, 0xc001608000, {0x3d8db30, 0xc0016ae348}, 0x15bc73?)
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/state/execution.go:307 +0x51d
 
 github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000708408, 0x7}}, {0xc000708440, 0x10}, 0x1, 0x15bc73, {{0xc001e00240, ...}, ...}, ...}, ...)
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/state/execution.go:140 +0x171
 github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc000708408, 0x7}}, {0xc000708440, 0x10}, 0x1, 0x15bc73, {{0xc001e00240, ...}, ...}, ...}, ...)
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/consensus/replay.go:503 +0x23c
 github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc000708408, 0x7}}, {0xc000708440, 0x10}, 0x1, 0x15bc73, {{0xc001e00240, ...}, ...}, ...}, ...)
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/consensus/replay.go:416 +0x7ae
 github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00159cf90, {0x3d8ff10, 0xc000744680})
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/consensus/replay.go:268 +0x3d4
 github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc000708408, 0x7}}, {0xc000708440, 0x10}, 0x1, 0x15bc73, ...}, ...)
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/node/node.go:329 +0x1b8
 github.com/tendermint/tendermint/node.NewNode(0xc0013baf00, {0x3d6f010, 0xc001b95860}, 0xc001e20ed0, {0x3d4f2a0, 0xc000d1e360}, 0x1?, 0x56fb460?, 0xc001e210e0, {0x3d78a48, ...}, ...)
  /root/go/pkg/mod/github.com/cometbft/cometbft@v0.34.28/node/node.go:779 +0x597
 github.com/zeta-chain/zetacore/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3da3320, 0xc001b798f0}, 0x0, {0xc001bc0320, 0x10}, {0x3d94cb8, ...}, ...}, ...)
  /go/src/github.com/zeta-chain/node/server/start.go:380 +0xf47
 github.com/zeta-chain/zetacore/server.StartCmd.func2(0xc001a80c00?, {0xc001b790e0?, 0x0?, 0x3?})
  /go/src/github.com/zeta-chain/node/server/start.go:164 +0x2a5
 github.com/spf13/cobra.(*Command).execute(0xc001a80c00, {0xc001b79050, 0x3, 0x3})
  /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
 github.com/spf13/cobra.(*Command).ExecuteC(0xc0015d4900)
  /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
 github.com/spf13/cobra.(*Command).Execute(...)
  /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
 github.com/spf13/cobra.(*Command).ExecuteContext(...)
  /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
 github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x26b0dc0?, {0x0, 0x0}, {0xc0015d0000, 0x15})
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.13/server/cmd/execute.go:36 +0x20f
 main.main()
  /go/src/github.com/zeta-chain/node/cmd/zetacored/main.go:19 +0x35
```

**Comment by lumtis** [comment]
It was the error we got during the upgrade, we had a hotfix for it. I will check if it has been ported to 12.0.4

**Comment by troykessler** [comment]
Getting the same issue

**Comment by fadeev** [comment]
@CryptoFewka @lumtis can you, please, provide guidance on how to upgrade from v11.0.0 at height 1424500 to the next version? 🙏

**Comment by CryptoFewka** [comment]
Hey @troykessler, you will want to use this upgrade path specifically, and not use the 12.0.4 binary at 1424500:
```
  Height  - Specific Zetacored Binary Version
1424500 - v12.0.0
1529050 - v12.1.0
1549750 - v12.2.1
```

**Comment by CryptoFewka** [comment]
I suspect we're missing the upgrade handler in zetacored v12.0.4, as that specific release was primarily focused on zetaclientd.

We may need to cut a v12.0.5 release or a hotfix release to avoid people being caught attempting the upgrade with v12.0.4. 

**TL&DR:** I expect that running zetacored version v12.0.0 at block 1424500 will get everyone attempting to sync from scratch successfully upgraded at block 1424500.

**Comment by troykessler** [comment]
> Hey @troykessler, you will want to use this upgrade path specifically, and not use the 12.0.4 zetacored binary at 1424500:
> 
> ```
> Height, Specific Zetacored Binary Version
> 1424500, v12.0.0
> 1529050, v12.1.0
> 1549750, v12.2.1
> ```

I would propose documenting this in the official docs (like here: https://www.zetachain.com/docs/validators/running-a-full-node/) since multiple upgrades already occurred it's difficult to find out which version was used for genesis and with which version to upgrade when.

**Comment by fadeev** [comment]
@CryptoFewka do we have an update on this? 🙏

**Comment by fadeev** [comment]
We need a definitive working upgrade path from block 0 to the current mainnet, so that Kyve can sync successfully.

**Comment by CryptoFewka** [comment]
The upgrade path for Mainnet zetacored is: 
0 - v10.1.0
1257000 - v11.0.0
1424500 - v12.0.0
1529050 - v12.1.0
1549750 - v12.2.1

**Comment by fadeev** [comment]
@CryptoFewka @lumtis @brewmaster012 

Feedback:

> Most users will start from the newest available patch version like me and run into the error where they have to sync from genesis again once they find out

Does it make sense for us to release the latest patch version (v10.1.8, v11.0.6, etc.) that matches the one that users should be using for each upgrade height?

**Comment by CharlieMc0** [comment]
This is what worked for them on mainnet 

```
Upgrade history
0 - v10.1.5
1257000 - v11.0.5
1424500 - v12.0.x

v12.0.0 -> panic: runtime error: index out of range [0] with length 0 
v12.0.1 -> panic: runtime error: index out of range [0] with length 0 
v12.0.2 -> works
v12.0.3 -> panic: runtime error: index out of range [0] with length 0 
v12.0.4 -> panic: runtime error: index out of range [0] with length 0
```

To make it easier to mainet and help others sync from 0 we should probably make a v12.0.5 release that works correctly. It's unclear why only v12.0.2 works here. CC @lumtis

**Comment by CharlieMc0** [comment]
Looks like a fix to the migration script was included in v12.0.2 but not any of the following versions. 

https://github.com/zeta-chain/node/compare/v12.0.0...v12.0.2
