### ISSUE TITLE
Improve error messages for RPC failures

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#1869]
**Describe the Issue**

If zetaclient crashes because of a connected RPC is should be very clear in the logs which chain is involved, why it crashed, what response it got from the RPC before failing, and if it crashed because of a specific transactions or not. 

Example: 
```
{"level":"info","chain":"mumbai_testnet","module":"ObserveOutTx","time":"2024-03-09T16:19:57Z","message":"observeOutTx: confirmed outTx 0xe9bb362600a6869f2b17c04b79d0641fb79612b6c36c361c7607d50d569b0245 for chain 80001 nonce 196164"}
{"level":"info","chain":"mumbai_testnet","module":"ObserveOutTx","time":"2024-03-09T16:19:57Z","message":"observeOutTx: confirmed outTx 0x076a40b965f0824c0c6e00ab4127554dc540fe85926f65f9d6c423d7d3ddbcb5 for chain 80001 nonce 196165"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfe6464]
goroutine 758 [running]:
github.com/ethereum/go-ethereum/core/types.(*Transaction).Hash(0x40017555a8?)
	/root/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/types/transaction.go:361 +0x24
github.com/zeta-chain/zetacore/zetaclient/evm.(*ChainClient).observeERC20Deposited(0x40018f6f00, 0xa25f66, 0xa25fc9)
	/go/src/github.com/zeta-chain/node/zetaclient/evm/evm_client.go:1135 +0xab8
github.com/zeta-chain/zetacore/zetaclient/evm.(*ChainClient).observeInTX(0x40018f6f00, {{0x37b4ff8, 0x40010ffb00}, 0x1, {0x37a8500, 0x4001c177a8}, {0x4001afa600, 0x39, 0x1f4}, {0x40010ffb10, ...}, ...})
	/go/src/github.com/zeta-chain/node/zetaclient/evm/evm_client.go:971 +0x310
github.com/zeta-chain/zetacore/zetaclient/evm.(*ChainClient).ExternalChainWatcher(0x40018f6f00)
	/go/src/github.com/zeta-chain/node/zetaclient/evm/evm_client.go:864 +0x2b0
created by github.com/zeta-chain/zetacore/zetaclient/evm.(*ChainClient).Start
	/go/src/github.com/zeta-chain/node/zetaclient/evm/evm_client.go:293 +0x9c
2024-03-09 16:20:00,341 - ERROR - Command execution failed
zetaclientd.service: Main process exited, code=exited, status=1/FAILURE
```

**Expected Outcome**
When zetaclient panics because of an RPC endpoint it should be very clear which chain is the problem, what the RPC response was, and any other information that can aid an operator in diagnosing the problem and resolving it quickly.

**Comment by kingpinXD** [comment]
Also, there have been multiple improvements on the client to handle errors gracefully since the time this issue was created ,  @zeta-chain/devops. If there are still some situations where zetaclient panics instead of handling errors, which we need more logging info on, please add it to the description , and I can look into it
