### ISSUE TITLE
zetaclient crash: too many open files

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#58]
```
panic: open /home/ubuntu/.metacore/keyring-test/val.info: too many open files

goroutine 222 [running]:
github.com/Meta-Protocol/metacore/metaclient.(*Keys).GetSignerInfo(...)
        /home/ubuntu/meta-node/metaclient/keys.go:90
github.com/Meta-Protocol/metacore/metaclient.(*MetachainBridge).PostGasBalance(0xc0010ec200, {0x17b5f9a, 0x3}, {0xc00a1f8270, 0x12}, 0x5b272b)
        /home/ubuntu/meta-node/metaclient/tx.go:11 +0x20d
github.com/Meta-Protocol/metacore/metaclient.(*ChainObserver).PostGasPrice(0xc0000df400)
        /home/ubuntu/meta-node/metaclient/chain_client.go:287 +0x15b1
github.com/Meta-Protocol/metacore/metaclient.(*ChainObserver).WatchGasPrice(0xc0000df400)
        /home/ubuntu/meta-node/metaclient/chain_client.go:159 +0x69
created by main.CreateChainClientMap
        /home/ubuntu/meta-node/cmd/metaclientd/mock_multinode.go:145 +0x1ef

```

**Comment by CharlieMc0** [comment]
Addressed
